import = ["/home/carlos/.config/alacritty/.alacritty-colorscheme/themes/tokyo-night.toml"]

[cursor.style]
blinking = "Off"
shape = "Beam"

[font]
size = 13.0

[font.normal]
family = "JetbrainsMono Nerd Font"

[font.offset]
x = 0
y = 5

[window]
dynamic_padding = true
dynamic_title = true
title = "Alacritty"

[window.padding]
x = 15
y = 15

[keyboard]
bindings = [
	{ key = "Return", mods = "Control|Shift", action = "SpawnNewInstance" }
]
