#----------------------
#    Custom Picom
#----------------------

backend = "glx";
glx-no-stencil=true;
glx-copy-from-front=false;



#-----------------------
#	Opacity
#-----------------------

# general options

#active-opacity = 1;
inactive-opacity =0.95;
#frame-opacity = 1;
#inactive-opacity-overryde = false;
#blur-background = true;


blur-method = "dual_kawase";
blur-strength = 3;


# Specifics

opacity-rule = [ 	
	"85:class_g = 'URxvt'",
	"85:class_g = 'Alacritty' && focused",
	"70:class_g = 'Alacritty' && !focused"
];

blur-background-exclude = [
];


# fading

#fading = false;
#fade-delta = 4;
#no-fading-openclose = true;


# others 

detect-rounded-corners = true;
detect-client-opacity = true;

corner-radius = 6;

vsync=true;

# shadow

shadow = true;
shadow-radius = 10;
shadow-offset-x = -5;
shadow-offset-y = -5;
shadow-opacity = 0.5;
#shadow-red = 1.0;

shadow-exclude = [
];

